# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRSmarter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Masonry',                          '~> 0.6.3'

  # Pods for QRSmarter

  target 'QRSmarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QRSmarterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
